# Generated by Django 2.1.7 on 2019-02-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now=True, verbose_name='Data da Publicação')),
                ('title', models.CharField(db_index=True, max_length=140, verbose_name='Título')),
                ('text', models.TextField(verbose_name='Artigo')),
            ],
        ),
    ]
