# Generated by Django 2.1.7 on 2019-03-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='resume',
            field=models.TextField(default=None, verbose_name='Resumo'),
            preserve_default=False,
        ),
    ]
